name: Create Release on Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get Current Date
        id: get-current-date
        run: |
          echo "current_date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          zip -r EFI-${{ github.action_ref }}-${{ steps.get-current-date.outputs.current_date }}.zip ./EFI

      - name: Generate Release Notes
        id: generate-release-notes
        run: |
          RELEASE_NOTES=$(git log --merges --oneline --format="- %s (%h)" $(git describe --tags --abbrev=0)..HEAD)
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT

      - name: Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          body: ${{ steps.generate-release-notes.outputs.release_notes }}
          files: EFI-${{ github.ref }}-${{ steps.get-current-date.outputs.current_date }}.zip
